repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: format-pnpm
        name: Format pnpm
        language: system
        entry: cd client && pnpm run format
        files: .*
      - id: format-go
        name: Format go
        language: system
        entry: gofumpt -l
        files: \.go$
