name: Deploy worker

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Git ref to deploy from (refs/tags/v* for tag)'
        default: 'refs/heads/main'
      commit:
        description: 'Commit SHA to deploy from (optional)'
      user:
        description: 'The username to use for the worker using SSH'
      server:
        description: 'The IP address or DNS hostname of the target server'
      environment:
        description: 'Environment to deploy to'
        required: true
        default: staging
        type: choice
        options:
          - staging
          - production

# Construct a concurrency group to be shared across workflow runs.
# The default behavior ensures that only one is running at a time, with
# all others queuing and thus not interrupting runs that are in-flight.
concurrency: ${{ github.workflow }}

permissions:
  contents: read

jobs:
  echo-inputs:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Echo Inputs
        run: |
          echo ref: ${{ github.event.inputs.ref }}
          echo commit: ${{ github.event.inputs.commit }}

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check out specific ref
        if: ${{ github.event_name == 'workflow_dispatch' }} && ${{ inputs.ref != ''}}
        run: git checkout ${{ inputs.ref }}

      - name: Check out specific commit
        if: ${{ github.event_name == 'workflow_dispatch' }} && ${{ inputs.commit != ''}}
        run: git checkout ${{ inputs.commit }}
        
      - name: Install Nomad
        env:
          NOMAD_VERSION: "1.4.1"
        run: |
          curl -Os https://releases.hashicorp.com/nomad/${NOMAD_VERSION}/nomad_${NOMAD_VERSION}_linux_$(dpkg --print-architecture).zip
          unzip nomad_${NOMAD_VERSION}_linux_$(dpkg --print-architecture).zip -d /usr/local/bin
          chmod +x /usr/local/bin/nomad
        
      - name: Deploy
        shell: bash
        run: |
          mkdir ~/.ssh
          eval `ssh-agent -s`

          case "${{ github.event.inputs.environment }}" in
          production)
            export INGRESS_DROPLET_IP="${{ secrets.INGRESS_DROPLET_IP_PRODUCTION }}"
            ssh-add - <<< "${{ secrets.DROPLET_SSH_PRIVATE_KEY_PRODUCTION }}"
            ;;
          staging)
            export INGRESS_DROPLET_IP="${{ secrets.INGRESS_DROPLET_IP_STAGING }}"
            ssh-add - <<< "${{ secrets.DROPLET_SSH_PRIVATE_KEY_STAGING }}"
            ;;
          *)
            echo "Unknown deploy environment"
            exit 1
            ;;
          esac

          ssh-keyscan -H $INGRESS_DROPLET_IP >> ~/.ssh/known_hosts
          # open ssh tunnel for nomad and vault
          ssh -fN -v -L 4646:127.0.0.1:4646 -L 8200:127.0.0.1:8200 root@$INGRESS_DROPLET_IP
        
          nomad run \
            -var "user=${{ inputs.user }}" \
            -var "server=${{ inputs.server }}" \
            -var "temporal_host_port=${INGRESS_DROPLET_IP}:7233" \
            -var "backend_fqdn=https://www.${INGRESS_DROPLET_IP}.sslip.io" \
            -var "commit_sha=$(git rev-parse HEAD)" \
            deploy/worker.nomad
